(use-modules (ice-9 format))

(define (years n m)
    (if (> n m)
        '()
        (cons n (delay (years (+ n 1) m)))))

(define (getEasterFor y)
    (let* ((g (+ (remainder y 19) 1))
           (c (+ (quotient y 100) 1))
           (x (- (quotient (* 3 c) 4) 12))
           (z (- (quotient (+ (* 8 c) 5) 25) 5))
           (d (- (quotient (* 5 y) 4) x 10))
           (et (remainder (- (+ (* 11 g) 20 z) x) 30))
           (e (if (or (and (= et 25) (> g 11)) (= et 24))
                 (+ et 1) et))
           (nfmt (- 44 e))
           (nfm (if (< nfmt 21) (+ nfmt 30) nfmt))
           (n (- (+ nfm 7) (remainder (+ d nfm) 7))))
          (list (if (> n 31) (- n 31) n) (if (> n 31) "April" "March") y)))

(define (eastersFor testyears)
    (if (null? testyears)
        '()
        (let ((head (car testyears)))
            (cons (getEasterFor head)
                (delay (eastersFor (force (cdr testyears))))))))

(define (output l)
  (if (null? l)
      '()
      (begin
        (let* ((easter (car l))
               (d (list-ref easter 0))
               (m (list-ref easter 1))
               (y (list-ref easter 2)))
              (display (format #f "   ~2,'0d ~a, ~4'0d\n" d m y))
              (output (force (cdr l)))))))

(display "Easters:\n") (output (eastersFor (years 1950 2050)))
