/**
 * Language icon file names keyed by language identifier.
 * Used by the Smoke Controls and Environment Init panes to resolve
 * the icon image for each language entry.
 *
 * @type {Record<string, string>}
 */
const LANGUAGE_ICON_FILE_BY_KEY = {
  ada: "ada.svg",
  arm64asm: "assembly.svg",
  asm: "assembly.svg",
  ballerina: "ballerina.svg",
  c: "c.svg",
  clojure: "clojure.svg",
  cobol: "cobol.svg",
  cpp: "cpp.svg",
  csharp: "csharp.svg",
  d: "d.svg",
  dart: "dart.svg",
  eiffel: "eiffel.svg",
  elixir: "elixir.svg",
  erlang: "erlang.svg",
  factor: "factor.svg",
  forth: "forth.svg",
  fortran: "fortran.svg",
  freebasic: "freebasic.svg",
  fsharp: "fsharp.svg",
  gleam: "gleam.svg",
  go: "go.svg",
  haskell: "haskell.svg",
  haxe: "haxe.svg",
  icon: "icon.svg",
  idris: "idris.svg",
  java: "java.svg",
  javascript: "javascript.svg",
  julia: "julia.svg",
  kit: "kit.svg",
  kotlin: "kotlin.svg",
  llvmir: "llvm.png",
  lua: "lua.svg",
  mercury: "mercury.svg",
  mmixal: "assembly.svg",
  modula3: "modula3.svg",
  mojo: "mojo.svg",
  nasm: "assembly.svg",
  nim: "nim.svg",
  oberon: "oberon.svg",
  objectivec: "objective-c.svg",
  ocaml: "ocaml.svg",
  octave: "octave.svg",
  pascal: "pascal.svg",
  perl: "perl.svg",
  php: "php.svg",
  prolog: "prolog.svg",
  python: "python.svg",
  r: "r.svg",
  racket: "racket.svg",
  ruby: "ruby.svg",
  rust: "rust.svg",
  scala: "scala.svg",
  scheme: "scheme.svg",
  simula: "simula.svg",
  smalltalk: "smalltalk.svg",
  swift: "swift.svg",
  tcl: "tcl.svg",
  typescript: "typescript.svg",
  v: "vlang.svg",
  visualbasic: "visualstudio.svg",
  wat: "webassembly.svg",
  zig: "zig.svg",
};

/**
 * Sample source file extensions keyed by language identifier.
 * Used by the Algorithms Run tree view to locate and display the
 * most representative source icon for each language.
 *
 * @type {Record<string, string>}
 */
const LANGUAGE_ICON_SAMPLE_EXTENSIONS = {
  ada: "adb",
  arm64asm: "s",
  asm: "asm",
  ballerina: "bal",
  c: "c",
  clojure: "clj",
  cobol: "cob",
  cpp: "cpp",
  csharp: "cs",
  d: "d",
  dart: "dart",
  eiffel: "e",
  elixir: "exs",
  erlang: "erl",
  factor: "factor",
  forth: "fth",
  fortran: "f90",
  freebasic: "bas",
  fsharp: "fs",
  gleam: "gleam",
  go: "go",
  haskell: "hs",
  haxe: "hx",
  icon: "icn",
  idris: "idr",
  java: "java",
  javascript: "js",
  julia: "jl",
  kit: "kit",
  kotlin: "kt",
  llvmir: "ll",
  lua: "lua",
  mercury: "moo",
  mmixal: "mms",
  modula3: "m3",
  mojo: "mojo",
  nasm: "nasm",
  nim: "nim",
  oberon: "mod",
  objectivec: "m",
  ocaml: "ml",
  octave: "mat",
  pascal: "pas",
  perl: "plx",
  php: "php",
  prolog: "pl",
  python: "py",
  r: "r",
  racket: "rkt",
  ruby: "rb",
  rust: "rs",
  scala: "scala",
  scheme: "scm",
  simula: "sim",
  smalltalk: "st",
  swift: "swift",
  tcl: "tcl",
  typescript: "ts",
  v: "v",
  visualbasic: "vb",
  wat: "wat",
  zig: "zig",
};

module.exports = {
  LANGUAGE_ICON_FILE_BY_KEY,
  LANGUAGE_ICON_SAMPLE_EXTENSIONS,
};
